// Copyright 2026 The Go Language Server Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package uri

import (
	"encoding/json"
	"errors"
	"os"
	"slices"
	"testing"

	"github.com/google/go-cmp/cmp"
)

type vectorFile struct {
	Parse              []parseVector `json:"parse"`
	Errors             []errorVector `json:"errors"`
	Paths              []pathVector  `json:"paths"`
	Generator          string        `json:"generator"`
	VscodeURIVersion   string        `json:"vscodeURIVersion"`
	GeneratedAt        string        `json:"generatedAt"`
	Contract           string        `json:"contract"`
	ReferenceGenerated []string      `json:"referenceGenerated"`
	Curated            []string      `json:"curated"`
	Note               string        `json:"note"`
}

type parseVector struct {
	Name             string     `json:"name"`
	Input            string     `json:"input"`
	Components       Components `json:"components"`
	String           string     `json:"string"`
	StringNoEncoding string     `json:"stringNoEncoding"`
	FsPathPOSIX      string     `json:"fsPathPOSIX"`
	FsPathWindows    string     `json:"fsPathWindows"`
}

type errorVector struct {
	Name   string `json:"name"`
	Input  string `json:"input"`
	Strict bool   `json:"strict"`
	Error  string `json:"error"`
}

type pathVector struct {
	Name     string   `json:"name"`
	Op       string   `json:"op"`
	URI      string   `json:"uri"`
	Segments []string `json:"segments"`
	Want     string   `json:"want"`
}

func TestVectors(t *testing.T) {
	vectors := readVectors(t)
	if vectors.Generator != "vscode-uri-canonical-reparse" {
		t.Fatalf("vectors generated by %q, want vscode-uri-canonical-reparse", vectors.Generator)
	}
	if vectors.VscodeURIVersion == "" {
		t.Fatal("vectors missing vscode-uri version")
	}
	if vectors.Contract != "go-comparable-canonical-uri" {
		t.Fatalf("vectors contract = %q, want go-comparable-canonical-uri", vectors.Contract)
	}
	if !slices.Contains(vectors.ReferenceGenerated, "parse.components.fromCanonicalReparse") {
		t.Fatalf("referenceGenerated = %v, want parse.components.fromCanonicalReparse", vectors.ReferenceGenerated)
	}
	if !slices.Contains(vectors.Curated, "errors") {
		t.Fatalf("curated = %v, want errors", vectors.Curated)
	}
	for _, v := range vectors.Parse {
		t.Run("parse/"+v.Name, func(t *testing.T) {
			t.Parallel()
			u, err := Parse(v.Input)
			if err != nil {
				t.Fatalf("Parse() error = %v", err)
			}
			if diff := cmp.Diff(v.Components, u.Components()); diff != "" {
				t.Fatalf("Components mismatch (-want +got):\n%s", diff)
			}
			if u.String() != v.String {
				t.Fatalf("String() = %q, want %q", u.String(), v.String)
			}
			if u.StringNoEncoding() != v.StringNoEncoding {
				t.Fatalf("StringNoEncoding() = %q, want %q", u.StringNoEncoding(), v.StringNoEncoding)
			}
			if v.FsPathPOSIX != "" {
				if got := FsPathFor(u, PlatformPOSIX, false); got != v.FsPathPOSIX {
					t.Fatalf("FsPathFor(POSIX) = %q, want %q", got, v.FsPathPOSIX)
				}
			}
			if v.FsPathWindows != "" {
				if got := FsPathFor(u, PlatformWindows, false); got != v.FsPathWindows {
					t.Fatalf("FsPathFor(Windows) = %q, want %q", got, v.FsPathWindows)
				}
			}
		})
	}

	for _, v := range vectors.Errors {
		t.Run("error/"+v.Name, func(t *testing.T) {
			t.Parallel()
			var err error
			if v.Strict {
				_, err = ParseStrict(v.Input)
			} else {
				_, err = Parse(v.Input)
			}
			if err == nil {
				t.Fatal("parse succeeded, want error")
			}
			if !errors.Is(err, sentinelForVectorError(t, v.Error)) {
				t.Fatalf("parse error = %v, want %q", err, v.Error)
			}
		})
	}

	for _, v := range vectors.Paths {
		t.Run("path/"+v.Name, func(t *testing.T) {
			t.Parallel()
			u := MustParse(v.URI)
			switch v.Op {
			case "join":
				got, err := JoinPath(u, v.Segments...)
				if err != nil {
					t.Fatalf("JoinPath() error = %v", err)
				}
				if got.String() != v.Want {
					t.Fatalf("JoinPath() = %q, want %q", got.String(), v.Want)
				}
			case "resolve":
				got, err := ResolvePath(u, v.Segments...)
				if err != nil {
					t.Fatalf("ResolvePath() error = %v", err)
				}
				if got.String() != v.Want {
					t.Fatalf("ResolvePath() = %q, want %q", got.String(), v.Want)
				}
			case "dirname":
				if got := Dirname(u).String(); got != v.Want {
					t.Fatalf("Dirname() = %q, want %q", got, v.Want)
				}
			case "basename":
				if got := Basename(u); got != v.Want {
					t.Fatalf("Basename() = %q, want %q", got, v.Want)
				}
			case "extname":
				if got := Extname(u); got != v.Want {
					t.Fatalf("Extname() = %q, want %q", got, v.Want)
				}
			default:
				t.Fatalf("unknown path op %q", v.Op)
			}
		})
	}
}

func readVectors(t *testing.T) vectorFile {
	t.Helper()
	data, err := os.ReadFile("testdata/vectors.json")
	if err != nil {
		t.Fatal(err)
	}
	var vectors vectorFile
	if err := json.Unmarshal(data, &vectors); err != nil {
		t.Fatal(err)
	}
	return vectors
}

func sentinelForVectorError(t *testing.T, s string) error {
	t.Helper()
	switch s {
	case ErrMissingScheme.Error():
		return ErrMissingScheme
	case ErrInvalidScheme.Error():
		return ErrInvalidScheme
	case ErrAuthorityPath.Error():
		return ErrAuthorityPath
	case ErrPathAuthority.Error():
		return ErrPathAuthority
	default:
		t.Fatalf("unknown vector error %q", s)
		return nil
	}
}
