// Copyright 2026 The Go Language Server Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Command gentables generates URI byte classification tables.
package main

import (
	"fmt"
	"strings"
)

const (
	classUnreserved = 1 << iota
	classPathExtra
	classAuthorityExtra
	classAlnum
	classHex
)

func main() {
	var classes [256]uint8
	for b := byte('a'); b <= byte('z'); b++ {
		classes[b] |= classUnreserved | classAlnum | classHex
	}
	for b := byte('A'); b <= byte('Z'); b++ {
		classes[b] |= classUnreserved | classAlnum | classHex
	}
	for b := byte('0'); b <= byte('9'); b++ {
		classes[b] |= classUnreserved | classAlnum | classHex
	}
	for _, b := range []byte{'-', '.', '_', '~'} {
		classes[b] |= classUnreserved
	}
	classes['/'] |= classPathExtra
	for _, b := range []byte{'[', ']', ':'} {
		classes[b] |= classAuthorityExtra
	}
	for _, b := range []byte("ABCDEFabcdef") {
		classes[b] |= classHex
	}

	var hex [256]uint8
	for i := range hex {
		hex[i] = 0xff
	}
	for i := range byte(10) {
		hex['0'+i] = i
	}
	for i := range byte(6) {
		hex['A'+i] = 10 + i
		hex['a'+i] = 10 + i
	}

	var pct strings.Builder
	for i := range 256 {
		fmt.Fprintf(&pct, "%%%02X", i)
	}

	fmt.Println("// Copyright 2026 The Go Language Server Authors. All rights reserved.")
	fmt.Println("// Use of this source code is governed by a BSD-style")
	fmt.Println("// license that can be found in the LICENSE file.")
	fmt.Println()
	fmt.Println("// Code generated by go run ./internal/gentables; DO NOT EDIT.")
	fmt.Println()
	fmt.Println("package uri")
	fmt.Println()
	fmt.Println("const (")
	fmt.Printf("\tcharClassUnreserved uint8 = %d\n", classUnreserved)
	fmt.Printf("\tcharClassPathExtra uint8 = %d\n", classPathExtra)
	fmt.Printf("\tcharClassAuthorityExtra uint8 = %d\n", classAuthorityExtra)
	fmt.Printf("\tcharClassAlnum uint8 = %d\n", classAlnum)
	fmt.Printf("\tcharClassHex uint8 = %d\n", classHex)
	fmt.Println(")")
	fmt.Println()
	printByteTable("uriCharClass", &classes)
	fmt.Println()
	printByteTable("hexDecodeTable", &hex)
	fmt.Println()
	fmt.Printf("const percentTriplets = %q\n", pct.String())
}

func printByteTable(name string, values *[256]uint8) {
	fmt.Printf("var %s = [256]uint8{\n", name)
	for row := range 16 {
		fmt.Print("\t")
		for col := range 16 {
			fmt.Printf("0x%02x, ", values[row*16+col])
		}
		fmt.Println()
	}
	fmt.Println("}")
}
